apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1dps
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-1dps@sha256:ba8c2edaea47bfe38046be310643e5128d956273108e11a4d3647c7b4b9a9c2e
        name: my-nodejs
        resources: {}
status: {}
